name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install buildozer
        pip install kivy
        pip install cython

    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-28" || true
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;27.0.3" || true

    - name: Build APK
      run: |
        buildozer android debug
