on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Buildozer & Cython
        run: |
          pip install buildozer
          pip install cython

      - name: Clean up build environment
        run: |
          buildozer appclean || true
          rm -rf ~/.buildozer || true

      # Install SDK Tools
      - name: Install SDK and Accept Licenses
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          yes | sdkmanager --licenses || true
          sdkmanager "platforms;android-28" "build-tools;35.0.0" --sdk_root=$ANDROID_HOME || true

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: bin/*.apk
